### ISSUE TITLE
Two paginators on the same page

### ISSUE THREAD

**Issue by maxmc** [lmcalpin/Play--Paginate#1]
Hi Lawrence, 
Firstly thanks for the great module!

Currently it seems impossible to employ two paginators on the same page as both are using the  configured paginator.parameter.name and there seems to be no option to assign a parameter.name to a specific paginator.

Cheers,
Max

**Comment by lmcalpin** [comment]
i just updated git hub with a fix to allow you to programmatically set the parameter name for a specific paginator. thanks for the report.

**Comment by maxmc** [comment]
thanks!
