### ISSUE TITLE
can't compile and debug from IDE

### ISSUE THREAD

**Issue by michael1976** [lmcalpin/Play--Paginate#16]
Since you're explicitly referencing JPA.getJPAConfig in JPARecordLocatorStrategy and it doesn't exist in play 1.2.x it's not possible to compile the project within an IDE. Would it be possible to update this line and use reflection similar to the line above?
`JPA.class.getMethod("getJPAConfig", String.class)`

**Comment by lmcalpin** [comment]
Done.
