### ISSUE TITLE
Tests from Paginate being run in play auto-test

### ISSUE THREAD

**Issue by mgonto** [lmcalpin/Play--Paginate#17]
Hi

I've the Play Paginate module installed, and each time I run play auto-test, a test from paginate is run and doesn't run ok.

What could this be?

Thanks!

**Comment by lmcalpin** [comment]
Were you using Play! 1.2.3 or earlier?  They worked on my machine, but I think older versions of Play! had a bug executing certain unit tests that use JPA.  At any rate, I removed them from the module, so they shouldn't impact anyone if they break again, for whatever reason.  I also updated the head release in the module repo.

**Comment by mgonto** [comment]
I'm using paginate-head with play 1.2.4. The tests used to work when everything was ok. I think that if there's an error in one of my tests, then Paginate tests fail as well. Otherwise it won't. 

Thanks for removing this!!
