### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by marcosnc** [lmcalpin/Play--Paginate#2]
Hi, I'm needing to add internationalization to your project, I've already done this on my dev environment, could I collaborate with you and upload my changes?

Best regards,
Marcos

**Comment by lmcalpin** [comment]
sure, did you fork the project on github and make the changes on that fork? you could then submit a pull request which would make it easy to integrate your changes with mine.  once i've done that i could upload it to the official Play! module repo.
