### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by mkotsur** [lmcalpin/Play--Paginate#4]
Seems that http://www.playframework.org/modules/paginate-head/home

contains wrong example:

Controller code

public static void index() {
      List<T> realList = ...;
      ValuePaginator paginator = new ValuePaginator(realList);
      render(paginator);
    }

Should obviously lead to template code:

```
#{paginate.list items:paginator, as:'r'} 
... ${r} // or whatever 
#{/paginate.list} 
#{paginate.controls items:paginator /} 
```

when example contains

```
 items:records
```

which is not correct.

**Comment by lmcalpin** [comment]
Fixed
