### ISSUE TITLE
new ModelPaginator(Foo.class, "foo=?", "bar") counts all rows in table

### ISSUE THREAD

**Issue by hlindquist** [lmcalpin/Play--Paginate#8]
Hi, I`m using Play 1.1 and when I used this method:
ModelPaginator entities = new ModelPaginator(Foo.class, "foo=?", "bar");
It took into consideration all rows in the table when counting max rows, so the paginator displayed too many pages.
When I used this method:
ModelPaginator entities = new ModelPaginator(Foo.class, keys);
Everything went fine.

It seems like a JPA bug and I caught this line in the sql log:
21:51:28,233 DEBUG ~ select count(*) as col_0_0_ from Post post0_ limit ?
I think this is the offending sql

Anyhow, thanks for a great plugin, it saved me alot of time. Wish I could abstract things like that!

**Comment by lmcalpin** [comment]
Nope, it was not a JPA bug. I checked in an update that should address this; the latest on github or official module repository should be good. If it doesn't, let me know and I'll work with you to fix it asap.

**Comment by hlindquist** [comment]
Thanks for fixing it, I can confirm that it works. I find it strange that you deprecated it at the same time though, it`s probably the least resource intensive method, isn`t it?

**Comment by lmcalpin** [comment]
It was deprecated because I thought the class had way too many constructors and I thought I would encourage the use of JPAIndexedRecordLocators instead, which allows you to do sorting in addition to filtering. But I will consider keeping it as a convenience.

**Comment by hlindquist** [comment]
Ok, some documentation of the JPAIndexedRecordLocator would be great. I see ModelPaginator has a constructor with JPAIndexedRecordLocator but it is also deprecated. Seems safe to use the deprecated ones then, so I`ll just do that ;)
